config/routes.rb
EdbryWeb::Application.routes.draw do
  resources :blog, controller: "posts", as: "posts" # this makes the "blog" paths *only* external. All internal paths and references are to "posts".
  resources :portfolio, controller: "projects", as: "projects" # same as above
  resources :users
  resources :password_resets, only: [:new, :edit, :update, :create], path_names: { new: "forgot_password", edit: "reset_password" }
  
  resources :sessions, only: [:new, :create, :destroy]
  match 'login' => 'sessions#new'
  match 'logout' => 'sessions#destroy'
  
  resources :pages
  get ':id' => "pages#show", as: 'view_page' # This needs to be last
  
  root to: 'pages#index'
end

app/views/pages/_index.html.erb
<nav>
  <a id="navAbout" href="/about">about</a>
  <a id="navPortfolio" href="/portfolio">portfolio</a>
  <a id="navProjects" href="/projects">projects</a>
  <a id="navBlog" href="/blog">blog</a>
  <a id="navContact" href="/contact">contact</a>
</nav>

app/views/pages/_page.html.erb
<h2><%= page.title %></h2>
<%= link_to "Edit Page", edit_page_path(page) if current_user %><br />

<%= page.content.html_safe %>

app/views/pages/_page_fields.html.erb
<%= check_for_errors page %>
<fieldset>
  <legend><%= page.new_record? ? "Add Page" : "Edit Page" %></legend>
  <ol>
  <li>
      <%= f.label :text_id, "Page Slug" %>
      <%= f.text_field :text_id, placeholder: "for the URL", disabled: !page.new_record? %>
    </li>
    <li>
      <%= f.label :title %> 
      <%= f.text_field :title %>
    </li>
  </ol>
  </fieldset>
  <fieldset>
    <ol>
      <li>
        <%= f.text_area :content, cols: nil, rows: "10" %>
      </li>
    </ol>
  </fieldset>
  <fieldset class="final">
    <ol>
      <li><%= f.submit %></li>
    </ol>
</fieldset>

app/views/pages/edit.html.erb
<%= form_for @page, html: { id: "edit_page" } do |f| %>
	<%= render partial: "page_fields", locals: { page: @page, f: f } %>
<% end %>

<p>
	<%= link_to "Delete this page", page_path(@page), method: 'delete', id: 'delete', confirm: "Are you sure you want to delete this page? All content will be lost." %>
</p>

app/views/pages/index.html.erb
<%= render 'index' %>

<%# This file is just for HTML requests %>

app/views/pages/index.js.erb
$("#page-content").html("<%=j render 'index' %>");

app/views/pages/new.html.erb
<%= form_for @page, html: { id: "new_page" } do |f| %>
	<%= render partial: "page_fields", locals: { page: @page, f: f } %>
<% end %>

app/views/pages/show.html.erb
<h2><%= @page.title %></h2>
<%= link_to "Edit Page", edit_page_path(@page) if current_user %><br />

<%= @page.content.html_safe %>

app/views/pages/show.js.erb
$("#page-content").html("<%=j render @page %>");